<a href="https://colab.research.google.com/github/vcdemy/20240116/blob/main/20240123%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20240123 筆記

In [ ]:
from keras.models import load_model  # TensorFlow is required for Keras to work
from PIL import Image, ImageOps  # Install pillow instead of PIL
import numpy as np

In [ ]:
# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model
model = load_model("keras_model.h5", compile=False)

# Load the labels
class_names = open("labels.txt", "r").readlines()

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

# Replace this with the path to your image
image = Image.open("data/glass/glass110.jpg").convert("RGB")

# resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)

# turn the image into a numpy array
image_array = np.asarray(image)

# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

# Load the image into the array
data[0] = normalized_image_array

# Predicts the model
prediction = model.predict(data)
index = np.argmax(prediction)
class_name = class_names[index]
confidence_score = prediction[0][index]

# Print prediction and confidence score
print("Class:", class_name[2:], end="")
print("Confidence Score:", confidence_score)




1/1 [==============================] - 1s 976ms/step
Class: Glass
Confidence Score: 0.7306934


In [ ]:
import gradio as gr

In [ ]:
def predict(image):
    # Disable scientific notation for clarity
    np.set_printoptions(suppress=True)

    # Load the model
    model = load_model("keras_model.h5", compile=False)

    # Load the labels
    class_names = open("labels.txt", "r").readlines()

    # Create the array of the right shape to feed into the keras model
    # The 'length' or number of images you can put into the array is
    # determined by the first position in the shape tuple, in this case 1
    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

    # Replace this with the path to your image
    # image = Image.open("data/glass/glass110.jpg").convert("RGB")

    # resizing the image to be at least 224x224 and then cropping from the center
    size = (224, 224)
    image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)

    # turn the image into a numpy array
    image_array = np.asarray(image)

    # Normalize the image
    normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

    # Load the image into the array
    data[0] = normalized_image_array

    # Predicts the model
    prediction = model.predict(data)
    index = np.argmax(prediction)
    class_name = class_names[index]
    confidence_score = prediction[0][index]

    # Print prediction and confidence score
    print("Class:", class_name[2:], end="")
    print("Confidence Score:", confidence_score)
    return class_name[2:], confidence_score

In [ ]:
gr.Interface(predict, gr.Image(type='pil'), ['text', 'text']).launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


1/1 [==============================] - 1s 1s/step
Class: cardboard
Confidence Score: 0.99991465
1/1 [==============================] - 1s 1s/step
Class: Plastic
Confidence Score: 0.9992405


In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 2], [3, 4]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
x.shape

(2, 2)

In [ ]:
x.reshape((1, 2, 2))

array([[[1, 2],
        [3, 4]]])

In [ ]:
y = x.reshape((1, 2, 2))

In [ ]:
x[0]

array([1, 2])

In [ ]:
y[0]

array([[1, 2],
       [3, 4]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
x1 = x*2

In [ ]:
x2 = x*3

In [ ]:
z = np.array([x1, x2])

In [ ]:
z.shape

(2, 2, 2)

# YOLO v5

https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading/#simple-example

In [ ]:
import cv2
import torch
from PIL import Image

In [ ]:
# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Images
for f in 'zidane.jpg', 'bus.jpg':
    torch.hub.download_url_to_file('https://ultralytics.com/images/' + f, f)  # download 2 images
im1 = Image.open('zidane.jpg')  # PIL image
im2 = cv2.imread('bus.jpg')[..., ::-1]  # OpenCV image (BGR to RGB)

# Inference
results = model([im1, im2], size=640)  # batch of images

# Results
results.print()
results.save()  # or .show()

results.xyxy[0]  # im1 predictions (tensor)
results.pandas().xyxy[0]  # im1 predictions (pandas)